version: "3"

services:
  mysql:
    container_name: arbeitsprobe-mysql
    build:
      context: .
    depends_on:
      - php
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arbeitsprobe
      MYSQL_DATABASE: arbeitsprobe
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
  php:
    build:
      context: .
    container_name: arbeitsprobe-php
    volumes:
      - "./www:/var/www/html"
    ports:
      - "80:80"
    networks:
      - backend
networks:
    backend:
        driver: bridge